### PR TITLE
Publish refine

### PR DESCRIPTION
**Pull request by ptpham**
Updating publish to reflect differentiation between the "vanilla" reference and the basis reference which incorporates refinement. Also switching to a much simpler way of accounting for thickness. Still doesn't give the desired result on the heart model, but it should be more stable.

### CODE REVIEW

**Comment by ptpham** [comment]
Try the heart with refine = 1!

**Comment by cixzhang** [comment]
Err, I can't tell the difference xD

**Comment by ptpham** [comment]
Mm ... well, without this diff, refine = 1 creates lots of badness. XD

**Comment by cixzhang** [comment]
Ah okay :P

**Comment by cixzhang** [comment]
So it looks good but how would one decide to use refine vs not use refine?

**Comment by ptpham** [comment]
Um ... I'm thinking we just make it manditory in the future. But we'll need to change the refinement to something else. This refinement isn't good enough. =P

**Comment by cixzhang** [comment]
Sounds good.

**Pull request merged**
