### PR TITLE
Animation fix for heart model

### PR DESCRIPTION
**Pull request by cixzhang**
Here's the fix I made. I also added tests so we can catch these cases. The heart model in the tests was taken from the old heart model and cleaned up. I think they look right. The heart model produced from this fix looks good in the viewer.

### CODE REVIEW

**Comment by ptpham** [comment]
I believe your fix is correct for the heart model, but it doesn't seem to preserve the intent of the original. The idea (that I should have commented on XD) was that the parent property represents the fold that future folds should be based off of. If the parent property is ignored, then repeated undo calls will try to "recursively undo" if that makes sense. =P

On the testing front, I think your chai additions are good, but I'm a bit concerned about having the heart model as part of the main suite of tests because it is a bit slow. I'm not sure if mocha has a way to separate longer tests ...

**Comment by cixzhang** [comment]
Ah, I'll add a test case for repeated undos then. Anything else I should watch out for?

**Comment by ptpham** [comment]
Uh ... that's all I have at the moment. Let's chat more about this tomorrow to see if we can come up with a reasonable setup. I'll try to have the improved alignment by tomorrow as well.

**Comment by cixzhang** [comment]
- [ ] Add test case for multiple undos separated by folds
- [ ] Separate heart model test into integration test folder (test_ci)
- [ ] Add Travis CI config to also test the tests in test_ci folder

**Comment by cixzhang** [comment]
So, I've noticed a few things while working on this:

- Ending an animation with undos sometimes produce strange results.
- Some folds don't seem to do the right thing when undos exist. For example:

```js
var Kokorigami = require('./src/index.js');
var Animation = Kokorigami.Animation;
var publish = Kokorigami.publish;

var animation = new Animation(3)
      .basic([.5, 1,0], [.5, 0,0]).fold()
      .basic([ 1,.5,0], [ 0,.5,0]).fold()
      .undo(2)
      .basic([ 1,0,0], [ 0,1,0]).fold();

var model = publish(animation);
console.log(JSON.stringify(model));
module.exports = model;
```

This will show strange results after the second fold. Doing this without an undo seems fine. This looks even stranger on master.

**Comment by ptpham** [comment]
I think this is the edge consistency bug I described earlier (i.e. the last fold in the sequence is missing some of the edges necessary in the sequence) ... should I switch to this bug instead of the alignment?

**Comment by cixzhang** [comment]
I think I managed to work around it. It makes the test I added a bit delicate though.

**Comment by ptpham** [comment]
Sounds good! We can probably make the test tougher in the future. =D

**Comment by ptpham** [comment]
Nice! =D =D =D =D

**Pull request merged**
